language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- '3.9-dev'
addons:
  apt:
    packages:
    - graphviz
before_install:
- export MPLBACKEND=Agg
install:
- sudo apt-get update
- python --version
- which python
- pip install .[testing]
- if [ '$TRAVIS_PYTHON_VERSION' = '3.6']; then pip install .[docs]; fi
script: make tests
after_success:
- coveralls
git:
  depth: 3
env:
  global:
    secure: byc2wWgxM4rrewNYwvJymK0TQOwqxufcHtv2u82fJ9lHZMtduztOlRemFQyRTzC6iqgQucVZtYu0E1+GWnzdwRZKQ2mvMNcMhcaaoNN9CjIjkjauFFJKGgwKRvUc4SeopDsDN7eVBai3L/gmghlYkKY192HS7uKemwW0TD17WwWCxBqYMI3X9BpxqYxXKxMTRLwI838dvfo7Ab8LHsdPPEcfH5wq2Z6NW6iMIWYFEKzCwt08NFfTXfb3zLar2jKntFN/H2Zn4x/JswKeFFcvyxJud4MrHOt6ckyuVKd07M6RjROC50CwCMfIe7ZC1BWmqZyE/ib+xCz3ATJ4Bv1omiH5aIexPrvi6RE33WGguDWWg1/lbsvZWOM+SG+nStBmiUT+lT7Ap/o/a1X7u4hdRAmkh6sXUUji/0TL0kjDoKa7J4p8BqoWxbyeDgAWu+EB8CjhL+8toSPV7/FhxSlMV9RncyfK1Aix1iJ9JSZ+PNli/1q0Do29Tbt3dKO2N+9wvdlADwbzpm/WlOLgY58y81NVQUZMwp3+L55cnvVe7XnjV72PnV7n1k1oJ9PoAnvWVQaY5TAPEmd3NDUeaqgIhlF6IXtF1lrJUXXibPQ3HW47BSwskpwnaMNmG7IOBQjj+B3B+qDUIyndSGDcauNmg69gNK8DdrfzA8OWkvlvRcQ=
deploy:
  provider: pypi
  user: tetamusha
  password:
    secure: s16kDeSssKMH2mktNDho8nUmVXYFb7OhetMi/ZKl4L0fWaAK8mi/zHRgQCyEF4nOBXZQIiWZJK3eeC0BTKjRopvs6hdLI2P4/FyCgPXLRUiCnC1a6IlwLK/VAiXCdx6vgtlec6m7Lfn80EuL8muwT6+ezY3a2niiDy6oNaY61sjpUqCl6+v8VIlDDOwOf/1NPfbMyhTCLYMl6rf6l/phap+PDuvoDu9l2K7pLXROyH/DtjEHuECsPhNWbmB5wzMeirnfMB23qhD2ibJJIZU3eTQliG07JzVjiNcHmOLAKBUtJoSNrF8RcgphOfB/pnWJYxdzDmhlXWkhrvK500Q+RJBDSbtscNlDPRqCv60VMUZ2tWXsHXaXSe4dsVhIG6sr88zuvPKm4QoUOxm9KkzH/Ybh+ySpirTVWhrjK6UYKTOc5QDvshQryrf2keNAgHF8MznM/yqh0txYIiyAM/RLKv00aCqaBvumvN2HQNPOmouTWM+tZtL3I86iQhf9MdSniRfwYp1f9A3HmruvEc0N9Eaw/VPjOzKvoxwOK8uxr82yZ3wL9V/oTjwHKQ9k1HobKKqWmZzxicUDmFDcUlL1u0X/oh54PYSvLUJpIeOvECdCJQn9SLHFq0A2J5W1u7Omq3E5iw4j+rbQjdymZJzqzNfapueuIPjgQ6PsJF6f0i0=
  on:
    condition: $TRAVIS_PYTHON_VERSION = 3.7
    tags: true
    repo: douglasrizzo/catsim
    distributions: sdist bdist_wheel
